name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # test-time extras used in this project
          pip install pytest mlflow optuna openai pandas pyarrow pybroker

      - name: Set test environment
        shell: bash
        env:
          OPENAI_API_KEY: sk-test-00000000000000000000000000000000
          PYTHONWARNINGS: ignore
        run: |
          python -c "import sys,platform; print('Python', sys.version); print('Platform', platform.platform())"
          python -c "import pandas,pyarrow; print('pandas', pandas.__version__, 'pyarrow', pyarrow.__version__)"
          pip freeze | sed -n '1,120p'

      - name: Run tests (pytest)
        shell: bash
        run: |
          mkdir -p artifacts/_ci
          # verbose to capture more details
          pytest -vv --durations=25 --maxfail=1 || echo "PYTEST_FAILED=1" >> $GITHUB_ENV
          # Save basic artifacts even if pass
          if [ -d artifacts/_quarantine ]; then cp -r artifacts/_quarantine artifacts/_ci/_quarantine; fi
          if [ -f companion/explorer/llm_logs.json ]; then cp companion/explorer/llm_logs.json artifacts/_ci/; fi

      - name: Upload CI artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/_ci
            logs
            .pytest_cache
            **/*.log
            **/mlruns/**

      - name: Fail if pytest failed
        if: env.PYTEST_FAILED == '1'
        run: |
          echo "::error::Pytest reported failures. See the 'ci-artifacts' artifact for logs/quarantine."
          exit 1
