name: Python

on:
  push:
  pull_request:

jobs:
  test-core:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mlflow dash plotly
      - name: Tests (core)
        run: |
          pytest -q
      - name: On fail: show MLflow dir
        if: failure()
        run: |
          dir artifacts\mlruns
  test-mlfinlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
      - name: Install minimal
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install "mlfinlab==1.8.2" || true
      - name: Labels/Meta smoke (skipped if no tests)
        run: |
          pytest -q -k "label or meta or mlfl" || true
