name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: "Install dependencies (with pybroker fallback stub)"
        shell: bash
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest mlflow optuna openai pandas pyarrow
          if ! pip install pybroker; then
            echo "pybroker wheel not found for this runner. Using CI stub."
            mkdir -p ci_vendor/pybroker
            printf "%s\n" "# CI stub for pybroker (imports only). Real package is used locally." > ci_vendor/pybroker/__init__.py
            echo "PYTHONPATH updated for pybroker stub."
            export PYTHONPATH="$PYTHONPATH:ci_vendor"
          fi

      - name: "Run tests (verbose) and collect reports"
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_TIMEOUT_MS: "20000"
        run: |
          pytest -v --maxfail=1 --disable-warnings -q || exit 1

      - name: "On fail: show MLflow dir"
        if: failure()
        shell: bash
        run: |
          echo "==== MLflow directory ===="
          ls -R artifacts/mlruns || true
