name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: |
          python -m pip install --upgrade pip
          # Install your project requirements if present (don’t fail CI if missing)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Test-time extras used in this project
          pip install pytest mlflow optuna openai pandas pyarrow pybroker

      - name: Set test environment
        env:
          # Prevent real LLM calls; your tests mock the client anyway
          OPENAI_API_KEY: sk-test-00000000000000000000000000000000
          # Quiet noisy warnings in CI logs (optional)
          PYTHONWARNINGS: ignore
        run: |
          python -c "import sys; print('Python', sys.version)"

      - name: Run tests
        run: |
          pytest -q
