name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (with pybroker fallback stub)
        shell: bash
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Core test deps
          pip install pytest mlflow optuna openai pandas pyarrow
          # Try pybroker; if not available on this runner, create a minimal stub so imports succeed
          if ! pip install pybroker; then
            echo "pybroker wheel not found for this runner. Using CI stub."
            mkdir -p ci_vendor/pybroker
            printf "%s\n" "# CI stub for pybroker (imports only). Real package is used locally." > ci_vendor/pybroker/__init__.py
            echo "PYTHONPATH=$PWD/ci_vendor:$PYTHONPATH" >> $GITHUB_ENV
          fi

      - name: Set test environment + quick diag
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONWARNINGS: ignore
        run: |
          # ensure repo root is importable
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
          python -c "import os,sys,platform; print('Python:', sys.version); print('Platform:', platform.platform()); print('OPENAI set:', bool(os.getenv('OPENAI_API_KEY')))"

      # ---------- NEW: sanitize problematic sources on runner ----------
      - name: Sanitize source encodings (remove null bytes)
        shell: bash
        run: |
          set -e
          python - <<'PY'
import pathlib, sys
p = pathlib.Path("companion/error_handling.py")
if not p.exists():
    sys.exit(0)
b = p.read_bytes()
nulls = b.count(b"\x00")
print("error_handling.py null bytes BEFORE:", nulls)
if nulls:
    # try UTF-16 first (common cause of \x00 on Windows)
    try:
        text = b.decode("utf-16")
    except Exception:
        text = b.decode("utf-8", "ignore").replace("\x00", "")
    p.write_text(text, encoding="utf-8")
    print("Sanitized error_handling.py to UTF-8")
# also purge pyc caches
for d in pathlib.Path(".").rglob("__pycache__"):
    try:
        for q in d.iterdir():
            q.unlink()
        d.rmdir()
    except Exception:
        pass
print("Sanitize step done.")
PY
      # ----------------------------------------------------------------

      - name: Run tests (verbose) and collect reports
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p artifacts/_ci
          pytest -vv -rA --durations=25 --maxfail=1 | tee artifacts/_ci/pytest-output.txt
          status=${PIPESTATUS[0]}
          # Collect helpful artifacts
          if [ -d artifacts/_quarantine ]; then cp -r artifacts/_quarantine artifacts/_ci/_quarantine; fi
          if [ -f companion/explorer/llm_logs.json ]; then cp companion/explorer/llm_logs.json artifacts/_ci/; fi
          if [ -d logs ]; then cp -r logs artifacts/_ci/logs; fi
          exit $status

      - name: Upload CI artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/_ci
            .pytest_cache
            **/*.log
